server:
  port: 8081

spring:
  application:
    name: auth-center
      
jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_here_should_be_at_least_32_characters_long}
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400

logging:
  level:
    com.auth: DEBUG
    org.springframework.security: INFO 