spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tars_admin
    username: tars_admin
    password: admin2447
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

security:
  permit-all-patterns:
    - "/swagger-ui/**"     # 전체 swagger-ui 경로
    - "/swagger-ui.html"   # 메인 swagger 페이지
    - "/v3/api-docs/**"    # OpenAPI 문서
    - "/swagger-resources/**"
    - "/webjars/**"
    - "/favicon.ico"
