server:
  port: 8081

spring:
  application:
    name: auth-center

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_here_should_be_at_least_32_characters_long}
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400

# 캐시 설정
app:
  cache:
    enabled: true
    ttl: PT30M # ISO-8601 기간 표기법: 30분
    token:
      access-token: PT1H # 1시간
      refresh-token: P14D # 14일
      blacklist: P7D # 7일
    user:
      profile: PT30M # 30분
      permissions: PT10M # 10분
    rate-limiting:
      login-attempts: PT30M # 30분
      api-requests: PT1M # 1분
      
springdoc:
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true # Group 활성화

  swagger-ui:
    display-request-duration: true # 요청 처리 시간 활성화
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    filter: true # 검색 필터 활성화
    deep-linking: true # URL에 태그와 작업 정보를 포함한 딥링크 활성화
    syntax-highlight:
      theme: monokai
    try-it-out-enabled: true
    default-models-expand-depth: 1
    default-model-expand-depth: 2 # (2: 속성까지 표시)
    urls-primary-name: "Latest Documentation" # 다중 문서 인터페이스의 기본 선택 문서 이름

  default-consumes-media-type: application/json # Default json
  default-produces-media-type: application/json

  group-configs:
    - group: user
      display-name: "User APIs"
      paths-to-match: /api/users/**
    - group: auth
      display-name: "Auth APIs"
      paths-to-match: /api/auth/**
    - group: admin
      display-name: "Admin APIs"
      paths-to-match: /api/admin/**

  mvc:
    problemdetails:
      enabled: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    default-property-inclusion: non_null

logging:
  level:
    root: INFO
    com.auth: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

packages-to-scan: com.auth.api.rest 